# Generated by Django 3.1.2 on 2020-11-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20201103_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
