# Generated by Django 3.1.2 on 2020-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20201105_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default-product-image.png', upload_to='media'),
        ),
    ]
